import type { Metadata } from "next";
import { Jomhuria, Jaro} from "next/font/google"; // Import the fonts
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Ticket App",
  description: "Generated by create next app",
};

// Initialize the JejuHallasan font

// Initialize the Jaro font
const jaro = Jaro({
  weight: "400", // Font weight (adjust as needed)
  subsets: ["latin"], // Subsets for the font
  variable: "--font-jaro", // CSS variable for Jaro
});

// Initialize the Jomhuria font
const jomhuria = Jomhuria({
  weight: "400", // Font weight (adjust as needed)
  subsets: ["latin"], // Subsets for the font
  variable: "--font-jomhuria", // CSS variable for Jomhuria
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-sans antialiased ${jomhuria.variable} ${jaro.variable}`}
      >
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
